onDragOver firefox issue
line 588: e.nativeEvent.target.className.indexOf(layoutClassName)
give "TypeError: e.nativeEvent.target.className.indexOf is not a function"

replaced by:
!e.nativeEvent.target.classList.contains(layoutClassName)